# Sample yml file.
language: c
sudo: required
compiler:
  - gcc
  - clang
script: make

deploy:
  provider: releases
  user: "sowani"
  password: "asowani123"
  file: "demo"
  skip_cleanup: true
  on:
    tags: true

